Backwards compatibility with previous version of ModLoader
Ijwu/PhoenixPointModLoader pull request #6
Opened 2020-02-15 17:45 UTC by pantolomin

Backwards compatibility with previous version of ModLoader so that players can safely migrate to the newest version. Hopefully modders will follow.

2020-02-18 06:49 UTC, Ijwu requested changes
Thanks a ton for this. I realize that my indescriminate obsolescence of legacy mods did not ring well with the community.

My only critical feedback is that the new `LegacyPhoenixPointMod` class should follow project conventions more closely. This isn't a PR killer, though, and if you're sick of me then I can do it--just let me know.

Thanks again for helping out! :)

2020-02-18 06:49 UTC, Ijwu commented on PhoenixPointModLoader/LegacyPhoenixPointMod.cs
> +    class LegacyPhoenixPointMod : IPhoenixPointMod
I like the idea of wrapping legacy mods with this class, clever! I understand it's nitpicking; please try to be consistent with  code conventions in the rest of the project. 

* Private fields should start with an underscore.
* Method names should be pascal case.

2020-02-18 06:49 UTC, Ijwu commented
P.S. sorry it took me so long to get to this. I've been unavailable for a while as I handle RL stuff.

2020-02-23 00:46 UTC, Ijwu commented
I'll go ahead and merge this and make the changes myself. 

Thanks again for your contribution.

2020-02-23 00:46 UTC, merged

2020-02-25 17:37 UTC, pantolomin commented
Oh, sorry. I hadn't seen that you wanted some modifications.
I'm a Java programmer so I don't know the writing conventions for C#. I learn some as I go.
It's really hard to go from one to an other.

2020-02-28 17:16 UTC, Ijwu commented
@pantolomin I totally understand. It's very minor things and I just went ahead and did it because I found some time to do so. No worries. :)